config/routes.rb
FOR2::Application.routes.draw do

  resources :users
  resources :cuisines
  resources :meals

  root :to => 'home#index'

  match '/login' => 'session#new', :via => :get
  match '/logout' => 'session#destroy', :via => :get
  match '/session' => 'session#create', :via => :post

  match '/users/:id/list' => 'users#list', :via => :get, :as => :user_list

  match '/auth/:provider/callback' => 'session#create'
  match '/auth/failure' => redirect('/')
  match '/signout' => 'session#destroy'

end

app/models/cuisine.rb
# == Schema Information
#
# Table name: cuisines
#
#  id           :integer          not null, primary key
#  cuisine_name :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Cuisine < ActiveRecord::Base
  has_and_belongs_to_many :meals
  has_and_belongs_to_many :users
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  def index
    @cuisines = Cuisine.all
  end

  def new
    @cuisine = Cuisine.new
  end

  def create
    @cuisine = Cuisine.new(params[:cuisine])
    if @cuisine.save
      redirect_to @cuisine
    else
      render :new
    end
  end

  def edit
    @cuisine = Cuisine.find(params[:id])
  end

  def show
    @cuisine = Cuisine.find(params[:id])
  end

  def update
    @cuisine = Cuisine.find(params[:id])
    if @cuisine.update_attributes(params[:cuisine])
      session[:cuisine_id] = @cuisine.id
      redirect_to @cuisine
    else
      render :edit
    end
  end

  def destroy
    cuisine = Cuisine.find(params[:id])
    cuisine.delete
    redirect_to cuisine
  end
end

app/views/cuisines/_formedit.html.erb
<%= form_for(@cuisine) do |f| %>
  <% if @cuisine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cuisine.errors.count, "error") %> prohibited this cuisine from being saved: </h2>

      <ul>
        <% @cuisine.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cuisine_name %>
    <%= f.text_field :cuisine_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/cuisines/_formnew.html.erb
<%= form_for(@cuisine) do |f| %>
  <% if @cuisine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cuisine.errors.count, "error") %> prohibited this cuisine from being saved: </h2>

      <ul>
        <% @cuisine.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cuisine_name %>
    <%= f.text_field :cuisine_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/cuisines/edit.html.erb
<h1>Edit Cuisine</h1>


<%= render 'formedit' %>


<!-- <h3>Do you want to be a seller?</h3><button id="show">Yes</button><br/>
<div id="seller_profile"><%#= render 'sellerprofile' %></div> -->


<%= link_to 'Back', cuisines_path %>



<p>Find me in app/views/cuisines/edit.html.erb</p>

app/views/cuisines/index.html.erb
<p>Find me in app/views/cuisines/index.html.erb</p>

<h1>The current list of cuisines are:</h1>

<h1><% @cuisines.each do |cuisine| %></h1>

<p><%= cuisine.cuisine_name %></p>





<td><%= link_to 'Show', cuisine_path(cuisine) %></td>
<td><%= link_to 'Edit', edit_cuisine_path(cuisine) %></td>
<td><%= link_to 'Destroy', cuisine, method: :delete, data: {confirm: 'Are you sure?'}%></td>
<% end %>

<br/>
<br/>
<br/>
<%= link_to 'Add New Cuisine', new_cuisine_path %>

app/views/cuisines/new.html.erb
<h3>Create a New Cuisine</h3>


<%= render 'formnew' %>


<p>Find me in app/views/cuisines/new.html.erb</p>

app/views/cuisines/show.html.erb
<%= link_to "logout", '/logout' %>

<%# if @auth %>
  <!-- <div><h2>Welcome<%#= @auth.first_name %></h2></div> -->
  <!-- <br> -->
<%# end %>

<h1>Your cuisine name is: <%= @cuisine.cuisine_name %></h1>


<%= link_to "Edit", edit_cuisine_path %><br/>
<%= link_to "Create New Cuisine", new_cuisine_path %><br/>
<%= link_to "Back to Index", cuisines_path %><br/>


<%# if @user.is_seller %>
    <%#= link_to "Post a Meal", new_meal_path %>
<%# end %>


<!-- <%#= meal_show_tag(@user) %>         #helper not working properly -->


<%# if @user.is_seller && @user.meals %>
  <!-- <h3>Your Posted Meals:</h3> -->
  <%# @user.meals.each do |meal| %>
  <!-- <%#= meal.meal_name %><br/> -->
  <%# end %>


<p>Find me in app/views/cuisines/show.html.erb</p>