config/routes.rb
FOR2::Application.routes.draw do

  resources :users
  resources :cuisines
  resources :meals

  root :to => 'home#index'

  match '/login' => 'session#new', :via => :get
  match '/logout' => 'session#destroy', :via => :get
  match '/session' => 'session#create', :via => :post

  match '/users/:id/list' => 'users#list', :via => :get, :as => :user_list

  match '/auth/:provider/callback' => 'session#create'
  match '/auth/failure' => redirect('/')
  match '/signout' => 'session#destroy'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                         :integer          not null, primary key
#  first_name                 :string(255)
#  last_name                  :string(255)
#  uid                        :string(255)
#  provider                   :string(255)
#  name                       :string(255)
#  username                   :string(255)
#  email_address              :string(255)
#  password_digest            :string(255)
#  zip_code                   :string(255)
#  phone_number               :string(255)
#  gender                     :string(255)
#  birthday                   :string(255)
#  buyer_fresh_preference     :string(255)
#  buyer_distance_preference  :integer
#  has_allergies              :boolean
#  seller_distance_preference :integer
#  seller_delivery_preference :boolean
#  seller_pickup_preference   :boolean
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#  is_seller                  :boolean
#  lat                        :float
#  lng                        :float
#

class User < ActiveRecord::Base
  # attr_accessible :title, :body
  has_secure_password
  has_and_belongs_to_many :cuisines
  has_and_belongs_to_many :meals

  def self.from_omniauth(auth)
  where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    user = User.new
    user.name = auth[:info][:name]
    user.username = auth[:info][:nickname]    #pulls Twiiter nickname and assigned FOR username
    user.uid = auth[:uid]
    user.provider = auth[:provider]
    user.password = "1234"
    user.password_confirmation = "1234"
    user.save
    user
  # create a new user, save provider, uid and name/nickname
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end


  def create
    @user = User.new(params[:user])
    if @user.zip_code != nil
    # the user's zipcode
    # take the user's zipcode
      @g = Geocoder.search(@user.zip_code)  # geocode the user's zipcode
      @lat = @g[0].data['geometry']['location']['lat'] # extract the geocoded lat/long
      @lng = @g[0].data['geometry']['location']['lng'] # save the lat/long to the user's lat/long
      @user.lat = @lat # user.lat = something
      @user.lng = @lng # user.lng = something
    end
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def login
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end


  def update

    @user = User.find(params[:id])
    if @user.zip_code != nil
    # take the user's zipcode
      @g = Geocoder.search(@user.zip_code)  # geocode the user's zipcode
      @lat = @g[0].data['geometry']['location']['lat'] # extract the geocoded lat/long
      @lng = @g[0].data['geometry']['location']['lng'] # save the lat/long to the user's lat/long
      @user.lat = @lat # user.lat = something
      @user.lng = @lng # user.lng = something
    end

    if @user.update_attributes(params[:user])
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :edit
    end
  end

  def list
    @user = User.find(params[:id])
    # @meals = Meal.order(params[:sort] + '' + params[:direction])        #sort table via arrows
    @meals = @user.cuisines.map(&:meals).flatten.uniq                   #prints meal name on list
    @sellers = @meals.map(&:users).flatten.uniq                         #prints seller name on list
    @meal_description = @meals.map(&:meal_description).flatten.uniq     #printsmeal_description
    # @meallist = Kaminari.paginate_array(@meals).page(params[:page]).per(10)
  end

  def destroy
    user = User.find(params[:id])
    user.delete
    redirect_to user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_buyerprofile.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved: </h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <% Cuisine.order('cuisine_name').each do |cuisine| %>
      <%= check_box_tag 'user[cuisine_ids][]', cuisine.id, @user.cuisines.to_a.include?(cuisine) %>
      <%= cuisine.cuisine_name %>
    <% end %>

  <div class="field">
    <%= f.label "What is your freshness preference?" %>
    <%= f.check_box :buyer_fresh_preference, :checked => true %><%= f.label "Same Day" %>
    <%= f.check_box :buyer_fresh_preference, :checked => false %><%= f.label "1-Day" %>
  </div>
  <div class="field">
    <%= f.label :buyer_distance_preference %>
    <%= f.text_field :buyer_distance_preference %>
  </div>
  <div class="field">
    <%= f.label "Do you have any allergies?" %>
    <%= f.radio_button :has_allergies, true %><%= f.label :has_allergies, "Yes" %>
    <%= f.radio_button :has_allergies, false %><%= f.label :has_allergies, "No" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_formedit.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved: </h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email_address %>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :birthday %>
    <%= f.text_field :birthday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/users/_formnew.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved: </h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email_address %>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :birthday %>
    <%= f.text_field :birthday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/users/_map.html.erb
<div id="map_canvas"></div>


<script>
  display_map(<%= lat %>, <%= lng %>, <%= zoom %>);
</script>

app/views/users/_pin.html.erb
<script>
  add_marker(<%= meal.lat %>, <%= meal.lng %>, '<%= meal.meal_name %>');
</script>

app/views/users/_sellerprofile.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved: </h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :seller_distance_preference %>
    <%= f.text_field :seller_distance_preference %>
  </div>
  <div class="field">
    <%= f.label "Do you deliver?" %>
    <%= f.radio_button :seller_delivery_preference, true %><%= f.label :seller_delivery_preference, "Yes" %>
    <%= f.radio_button :seller_delivery_preference, false %><%= f.label :seller_delivery_preference, "No" %>
  </div>
  <div class="field">
    <%= f.label "Can I pickup my meal?" %>
    <%= f.radio_button :seller_pickup_preference, true %><%= f.label :seller_pickup_preference, "Yes" %>
    <%= f.radio_button :seller_pickup_preference, false %><%= f.label :seller_pickup_preference, "No" %>
    <%= f.hidden_field :is_seller, :value => true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= link_to "logout", '/logout' %>

<h1>Edit Profile</h1><%= link_to "Cancel Edit", user_path %><br/><br/>

<%= render 'formedit' %>


<h3>Please complete your buyer profile and select the type of meals you prefer:</h3>
<div id="buyer_profile"><%= render 'buyerprofile' %></div>
<br/>

<h3>Do you want to be a seller?</h3><button id="show">Yes</button>
<div id="seller_profile"><%= render 'sellerprofile' %></div>



<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<%= link_to "logout", '/logout' %>

<%= @auth.try(:name) %>

<p>Find me in app/views/users/index.html.erb</p>

<h1>The current list of users are:</h1>

<h1><% @users.each do |user| %></h1>

<p><%= user.username %></p>
<td><%= link_to 'Show', user %></td>
<td><%= link_to 'Edit', edit_user_path(user) %></td>
<td><%= link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'}%></td>
<% end %>

<br/>
<br/>
<%= link_to 'New User', new_user_path %>

app/views/users/list.html.erb
<%= link_to "logout", '/logout' %>

<h1>Users#list</h1>

<%= link_to "Edit Your Meal Preferences", edit_user_path %><br/>

<h1>Meals based on your preferences</h1><br/>
<h2>Your current zip code is: <%= @auth.zip_code %></h2>
<br/>
<table class="Meals">
  <tr>
    <th>Meal Name</th>
    <th>Zip Code</th>
    <th>Seller</th>
    <th>Price</th>
    <th>Description</th>
    <th>Cuisine Types</th>
    <th>Approximate Distance</th>
  </tr>

<%= render :partial => 'map', :locals => {:lat => @user.lat, :lng => @user.lng, :zoom => 14} %>
<%= render :partial => 'pin', :collection => @meals, :as => :meal %>

<% @meals.each do |meal| %>
  <tr>
    <td><%= link_to meal.meal_name, meal_path(meal) %></td>
    <td><%= meal.users.first.zip_code %></td>
    <td><%= meal.users.first.username %></td>
    <td><p><%= number_to_currency(meal.meal_price) %></p></td>
    <td><%= meal.meal_description %></td>
    <td><%= meal.cuisines.map { |cuisine| cuisine.cuisine_name }.join(", ") %></td>
    <td><%= %></td>
  </tr>
  <% end %>
</table><br/>

<%#= paginate @meallist %>

<br/>
<br/>
<%= link_to "Edit Your Meal Preferences", edit_user_path %><br/><br/>

app/views/users/new.html.erb
<h1>Hey welcome to FOR</h1>


<h3>Create a New User</h3>


<%= render 'formnew' %>


<p>Find me in app/views/users/new.html.erb</p>


<%= link_to 'Login', login_path %>

app/views/users/show.html.erb
<%= link_to "logout", '/logout' %>

<% if @auth %>
  <div><h2>Welcome <%= @auth.first_name %></h2></div>
  <br>
<% end %>

<h1>Your username is: <%= @user.username %></h1>
<br/>
<br/>

<%= link_to "Edit Your Profile", edit_user_path %><br/><br/>
<%= link_to "Choose Your Meal Preferences", edit_user_path %><br/><br/>

<% if @user.cuisines != nil %>
  <%= link_to "Show me Meals", user_list_path %><br/><br/>
<% end %>


<% if @user.is_seller %>
    <%= link_to "Post a Dish", new_meal_path %>
<% end %>


<!-- <%#= meal_show_tag(@user) %>         #helper not working properly -->

<br/>
<br/>
<% if @auth.is_seller && @auth.meals %>
  <h3>Your Posted Meals:</h3>
  <% @user.meals.each do |meal| %>
  <%= meal.meal_name %>
  <%= link_to "Edit Dish", edit_meal_path(meal) %>
  <%= link_to 'Destroy', meal, method: :delete, data: {confirm: 'Are you sure?'}%><br/>
<% end %>




<p>Find me in app/views/users/show.html.erb</p>

<% end %>